### ISSUE TITLE
Config file fails to modify key shortcuts

### ISSUE THREAD

**Issue by denzilholles** [ijgnd/anki21__editor_add_hyperlink#1]
Hi, currently using Anki 2.1.11 (3cf770c7) on Mac OSX 10.14.1.

I tried modifying the key shortcut `"shortcut_insert_link": "Ctrl+Shift+H"` from `"Ctrl+Shift+H"` to `"Ctrl+R"` in `Add-ons > Config` but the new key shortcut fails to work. I also tried editing `meta.json` in the Add-on folder but that doesn't fix anything. Anyone have any suggestions?

**Comment by ijgnd** [comment]
- Just to be sure:  "Ctrl+Shift+H" works for you and the only problem is that "Ctrl+R" is not working?
- "Ctrl+R" (on windows/linux) is a built-in short cut to remove formatting: you can see this if you hover with your mouse over the button Fx (if B (bold) is the first button this "remove formatting" button is the sixth button from the left). The add-on can't overwrite such built-in commands
- I don't have a Mac. But as far as I know where on Linux/Windows you would use "Ctrl" on Mac you use "Cmd". If you set "Ctrl" in the deck settings Anki seems to automatically translate this to "Cmd" so that you might have to press "Cmd+R" or "Cmd+Shift+H", see https://anki.tenderapp.com/discussions/ankidesktop/30282-is-there-a-shortcut-for-mac-for-colors#comment_46398286

**Comment by denzilholles** [comment]
> Just to be sure: "Ctrl+Shift+H" works for you and the only problem is that "Ctrl+R" is not working?

Correct. 

> "Ctrl+R" (on windows/linux) is a built-in short cut to remove formatting: you can see this if you hover with your mouse over the button Fx (if B (bold) is the first button this "remove formatting" button is the sixth button from the left). The add-on can't overwrite such built-in commands

Since I've read your comment, I changed the key strokes in the config file to "Ctrl+X" and "Ctrl+Shift+X" but both fail to do anything (after restarting Anki etc). 

> I don't have a Mac. But as far as I know where on Linux/Windows you would use "Ctrl" on Mac you use "Cmd". If you set "Ctrl" in the deck settings Anki seems to automatically translate this to "Cmd" so that you might have to press "Cmd+R" or "Cmd+Shift+H", see https://anki.tenderapp.com/discussions/ankidesktop/30282-is-there-a-shortcut-for-mac-for-colors#comment_46398286

I'm using the Cmd key.

**Comment by ijgnd** [comment]
- "Ctrl+X" is the shortcut to cut the selected text. "Ctrl+Shift+X" is the shortcut to view the html source code of the current field. The add-on can't overwrite such built-in commands.
- This add-on uses the standard way of Anki to set shortcuts. I have no idea how this works internally and how you would have to unconnect shortcuts. There is a popular addon named [Customize Keyboard Shortcuts](https://ankiweb.net/shared/info/24411424) that allows you to rebind built-in commands. I have never used this add-on so I don't know if this frees up the shortcuts. You could try it and then check again if you can now use "Ctrl+Shift+X" to set hyperlinks.
- If a shortcut you set in this add-on is not working you could try to set this shortcut in a different add-on. If the shortcut is not working in the different add-on either this is a general problem about Anki and not about one add-on in particular. I don't know much about programming the user interface for Anki. It's likely that you'll get better answers in the official forum at anki.tenderapp.com or the anki subreddit. 
- if you have many add-ons it's sometimes difficult to find unused key combos. That's a limitation of Anki. But you can check which keys are already used for the editor (in the add window), see https://www.reddit.com/r/Anki/comments/8v8rya/anyone_know_of_a_good_way_on_a_mac_to_make_caps/e1lmjcr/   About the debug console see https://apps.ankiweb.net/docs/manual.html#debug-console

**Comment by denzilholles** [comment]
Yeah, that was a dumb mistake. I used a key combination that was random (Ctrl+G) and the config file was successful. Thanks for all of your help!
