### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by GrimPixel** [ijgnd/anki21__editor_add_hyperlink#12]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (81cc5a09) Python 3.10.1 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-01-25 08:28:02
Add-ons possibly involved: ⁨Add Hyperlink⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/editor.py", line 1302, in contextMenuEvent
    gui_hooks.editor_will_show_context_menu(self, m)
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 2273, in __call__
    anki.hooks.runHook("EditorWebView.contextMenuEvent", editor_webview, menu)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/grim/.local/share/Anki2/addons21/318752047/add_hyperlinks.py", line 121, in add_to_context
    context_request = view.lastContextMenuRequest()
AttributeError: 'EditorWebView' object has no attribute 'lastContextMenuRequest'

**Comment by ijgnd** [comment]
Thanks for the report. 

I adjusted this add-on to 2.1.50+qt6 and forgot that people still might use 2.1.50+qt5 ... Reverting https://github.com/ijgnd/anki21__editor_add_hyperlink/pull/10/commits/98946f928e347ef9a27562dcb2f21a2abbe6476f for qt5 should be the solution. I'll upload a new version in a few days.

**Comment by ijgnd** [comment]
the latest version should fix this. If the problem still persists after updating the add-ons and restarting anki please let me know (and reopen the issue).
