### ISSUE TITLE
Suggestion for autofilling fields

### ISSUE THREAD

**Issue by RandmTask** [ijgnd/anki21__editor_add_hyperlink#20]
Quick suggestion:

When highlighting in Anki then pressing the shortcut it autofills into the "Text To Display" field. Thats great, but usually I have pasted a link and I only want to put a name for the link only. So I need to copy and paste the link into the link field, and then fill in the text field
![CleanShot 2023-05-13 at 11 23 31](https://github.com/ijgnd/anki21__editor_add_hyperlink/assets/7912017/6da13617-67b6-418b-9975-ac183c093ebd)

Suggestion:
1. Detect whether it is a link or not. If it looks like a link, put it in the link field, if its text, put it into the text field.
2. Or an easier to implement (but less desirable) method would just be to fill in both fields with the same information, then we can delete as appropriate.

As an aside, there is a small typo for '**example**' here:
**prepend missing scheme (e.g. www.expample.com) with?**

Thank you for the work on the app

**Comment by ijgnd** [comment]
this sounds useful. Thanks for the suggestion and clear post. Also thanks for pointing me to the typo.

added with a621151

I just uploaded a new version to ankiweb. Update your addons and restart anki.

If you find problems let me know.

I'm closing this thread. Reopen it or make a new one.
