### ISSUE TITLE
Suggestion for auto-pasting

### ISSUE THREAD

**Issue by RandmTask** [ijgnd/anki21__editor_add_hyperlink#21]
Quick suggestion:

If no text or link is selected when you activate the addon from the shortcut, auto-paste the link or "Text to Display" from the clipboard

Thanks again for the add-on, it saves a lot of time!

**Comment by ijgnd** [comment]
this sounds useful. thanks for the suggestion.

added partially with 804d826  I only insert the clipboard contents if they look like a url.

I just uploaded a new version to ankiweb. Update your addons and restart anki.

If you find problems let me know.

I'm closing this thread. Reopen it or make a new one.
