### ISSUE TITLE
Mac usage?

### ISSUE THREAD

**Issue by ftrotter** [ijgnd/anki21__editor_add_hyperlink#3]
It is not at all clear how to install this Add On using the Mac OSX. 

There is no "Tools" menu that I can find. for instance.. and there are no manual installation instructions in the README on this repo.

-FT

**Comment by ijgnd** [comment]
Most users don't install add-ons from the github source but from the official add-on site https://ankiweb.net/shared/addons/2.1. 

Does this video help: https://youtu.be/1vefco4uwlk?t=11

&nbsp;

> there are no manual installation instructions in the README on this repo.

the repo here just mirrors what's on ankiweb. As far as I see, manually installing doesn't offer any benefits unless you want to modify the add-on. Even in this case you could also just change the add-on that you installed from ankiweb. 

&nbsp;

Some technical details:

About a year ago anki introduced a new addon packaging file type (zip files named ".ankiaddon" that contain a manifest.json file with two entries). Add-on creators who don't want their add-on on ankiweb listed use it, e.g. to sell their add-on or to distribute versions for testing. I didn't create such a file. If you really want to use it you could zip the contents of the folder "src" from this repo and name it hyperlink.ankiaddon. 

For a full manual install create a subfolder in your [addons21 folder in your anki profile](https://apps.ankiweb.net/docs/manual.html#file-locations) and copy the contents of the src folder from this repo into it and restart Anki.

Many repos for anki add-ons don't have manual install instructions. This approach "new folder in addons21 and copy the part of the github repo that contains an `__init__.py` file" works for most anki add-ons shared on github unless they contain user interface elements that need to be built with software from the underlying toolkit qt.
