### ISSUE TITLE
Feature Request : Clickable in browse mode 

### ISSUE THREAD

**Issue by havewisdom** [ijgnd/anki21__editor_add_hyperlink#5]
I don't think there is any other way.
I often use links, but the way to load them through a click is possible in review mode or preview mode. 
In my case,
The browse mode is mainly used for convenience such as editing and searching.
Isn't it possible to make a link clickable in Browse mode?

Thank you!

**Comment by ijgnd** [comment]
A simple left click would certainly be easier and probably better but it's not easy for me to implement this solution.  

Workaround: Right click and from the context menu select "Open URL". Since this workaround works well for me this enhancement has a low priority for me.

@tomkahn

**Comment by tomkahn** [comment]
I did not know that there was right click menu for this. I'm glad I asked. So thank you, once again!

Btw: This is probably also influenced by something outside of this addon: Anki 2.0 has clickable links everywhere.

**Comment by ijgnd** [comment]
the context menu option is from my add-on.
