### ISSUE TITLE
"?" being converted to "%3F"

### ISSUE THREAD

**Issue by Billboz** [ijgnd/anki21__editor_add_hyperlink#6]
Is there a way to escape the ? in the youtube URL?  It is changing and breaking the link.
Input URL:
https://www.youtube.com/watch?v=mbHnrAzKygg
"?"

What it is converted to after being saved.
https://www.youtube.com/watch%3Fv=mbHnrAzKygg
"%3F"

Thanks

**Comment by ijgnd** [comment]
Thanks for reporting this. I just uploaded a new version to ankiweb that should have fixed this. If the problem persists or you find other problems please let me know.
