### ISSUE TITLE
Could you support link to another card?

### ISSUE THREAD

**Issue by Juddd** [ijgnd/anki21__editor_add_hyperlink#9]
It is a wonderful add-on for url. But could you make it support link another anki card? As we know, every card have a unique **Note ID**, I don't know we can use it to realize...

**Comment by ijgnd** [comment]
Not in this add-on.

There are already two slightly different add-ons that should help:

- my [link Cards Notes and Preview them in extra window](https://ankiweb.net/shared/info/1423933177)
- Arthur's [Links between notes, cards, to open browser and previewer](https://ankiweb.net/shared/info/1126950429)
